Mvc3QA/Controllers/RecordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc3QA.Models;
using Mvc3QA.Models.Services;
using System.Web.Profile;
using System.Web.Security;
using System.Data.Entity.Validation;
using Common;

namespace Mvc3QA.Controllers
{
    //[Authorize(Roles = "BusinessUsers")]
    public class RecordsController : Controller
    {
        private questiononlineContext db = new questiononlineContext();

        //
        // GET: /RecordS/

        public ViewResult Index()
        {
            var pts_records = db.Pts_Records.Include(p => p.Pts_Problems).Include(p => p.Pts_ProblemState);
            return View(pts_records.ToList());
        }

        //
        // GET: /RecordS/Details/5

        public ViewResult Details(Guid id)
        {
            Pts_Records pts_records = db.Pts_Records.Find(id);
            return View(pts_records);
        }

        //其他部门人员回复问题
        // GET: /RecordS/Create

        public ActionResult Create(Guid id)
        {
            Pts_Records modelRecords = new Pts_Records();
            modelRecords.ProblemID = id;
            Department clsDepartment = new Department();
            UserProfileModel userprofile = GetMyProfile();
            ViewBag.AssignTo = new SelectList(clsDepartment.GetDepartmentList(userprofile.Department), "DeptID", "DeptName");
            return View(modelRecords);
        }

        //
        // POST: /RecordS/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Pts_Records pts_Records)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Pts_Records modelPts_Records = new Pts_Records();
                    var NewRecords = (from d in db.Pts_Records
                                      where d.ProblemID == pts_Records.ProblemID
                                      orderby d.CreateTime descending
                                      select d).First();
                    var LastRecords = (from d in db.Pts_Records
                                       where d.ProblemID == pts_Records.ProblemID
                                       orderby d.CreateTime ascending
                                       select d).First();
                    var upDateProblems = (from d in db.Pts_Problems
                                          where d.ProblemID == pts_Records.ProblemID
                                          select d).Single();
                    Department clsDepartment = new Department();
                    UserProfileModel userprofile = GetMyProfile();
                    if ((pts_Records.AssignType == 1) || (pts_Records.AssignType == 3))//直接解决或者不不解决转交上一个人
                    {
                        modelPts_Records.AssignTo = "1";
                        modelPts_Records.AssignType = 0;
                        modelPts_Records.AssignStateID = new Guid("00000000-0000-0000-0000-000000000000");

                        //根据问题最终处理人
                        if (NewRecords.Pts_ProblemState.ListOrder==1)
                        {
                            upDateProblems.SolveUser = User.Identity.Name;
                        }

                        if (LastRecords.CreateUser == User.Identity.Name || (GetUserDP(User.Identity.Name) == "bbf977d8-aeab-4bec-b070-a3d1c1b41cb5"))//第一条记录创建人和当前用户，判断是否是问题提交人GetUserDP(ReplayRecords.CreateUser)
                        {
                            modelPts_Records.AssignToObjectID = userprofile.NickName;
                            modelPts_Records.ProblemStateID = new Guid("aa36df43-a68b-45e2-8230-21b2f6f5fce2");//问题已解决
                            modelPts_Records.Course = "-->" + userprofile.NickName;
                            upDateProblems.IsClosed = true;
                        }
                        else
                        {
                            //上一个部门
                            Guid preDPID = clsDepartment.GetPreDeparmentID(userprofile.Department);

                            if (NewRecords.Pts_ProblemState.IsState == 2)//最新一条记录状态为待确定的
                            {
                                //获取当前记录的隔一条记录
                                var ReplayRecords = (from d in db.Pts_Records
                                                     where d.ProblemID == pts_Records.ProblemID && (d.ListOrder == NewRecords.ListOrder - 2)
                                                     orderby d.CreateTime descending
                                                     select d).First();
                                if (ReplayRecords.Pts_ProblemState.IsState == 2)
                                {//解决打回问题
                                    var ReplayRecordsDH = (from d in db.Pts_Records
                                                           where d.ProblemID == pts_Records.ProblemID && (d.ListOrder == ReplayRecords.ListOrder - 2)
                                                           orderby d.CreateTime descending
                                                           select d).First();
                                    modelPts_Records.AssignToObjectID = ReplayRecordsDH.CreateUser;
                                    modelPts_Records.Course = userprofile.NickName + "-->" + clsDepartment.GetDepartmentName(GetUserDP(ReplayRecordsDH.CreateUser)) + "(" + GetUserProfile(ReplayRecordsDH.CreateUser) + ")";
                                }
                                else
                                {
                                    modelPts_Records.AssignToObjectID = ReplayRecords.CreateUser;
                                    modelPts_Records.Course = userprofile.NickName + "-->" + clsDepartment.GetDepartmentName(GetUserDP(ReplayRecords.CreateUser)) + "(" + GetUserProfile(ReplayRecords.CreateUser) + ")";
                                }

                            }
                            else
                            {
                                modelPts_Records.AssignToObjectID = NewRecords.CreateUser;
                                modelPts_Records.Course = userprofile.NickName + "-->" + clsDepartment.GetDepartmentName(preDPID.ToString()) + "(" + GetUserProfile(NewRecords.CreateUser) + ")";

                            }

                            modelPts_Records.ProblemStateID = clsDepartment.GetProblemStateReplay(preDPID);
                        }

                        modelPts_Records.SrcUserID = NewRecords.CreateUser;
                    }
                    if (pts_Records.AssignType == 2)//转交其他人
                    {
                        modelPts_Records.AssignTo = pts_Records.AssignTo;
                        modelPts_Records.AssignToObjectID = pts_Records.AssignToObjectID;
                        modelPts_Records.AssignType = 2;
                        modelPts_Records.AssignStateID = new Guid("00000000-0000-0000-0000-000000000000");
                        modelPts_Records.ProblemStateID = clsDepartment.GetProblemState(pts_Records.AssignTo);
                        modelPts_Records.SrcUserID = NewRecords.CreateUser;
                        //提交问题记录相关信息
                        if (pts_Records.AssignToObjectID == "0")
                        {

                            modelPts_Records.Course = userprofile.NickName + "-->" + clsDepartment.GetDepartmentName(pts_Records.AssignTo) + "(部门所有人)";

                        }
                        else
                        {
                            modelPts_Records.Course = userprofile.NickName + "-->" + clsDepartment.GetDepartmentName(pts_Records.AssignTo) + "(" + GetUserProfile(pts_Records.AssignToObjectID) + ")";

                        }
                    }
                    modelPts_Records.RecordID = Guid.NewGuid();
                    modelPts_Records.Content = pts_Records.Content;
                    modelPts_Records.Describe = Utils.NoHTML(string.IsNullOrWhiteSpace(pts_Records.Content) ? "" : pts_Records.Content);
                    modelPts_Records.CreateUser = User.Identity.Name;
                    modelPts_Records.CreateTime = DateTime.Now;
                    modelPts_Records.ProblemID = pts_Records.ProblemID;
                    modelPts_Records.ListOrder = NewRecords.ListOrder + 1;
                    modelPts_Records.ResponseTotalTime = Utils.TimeDifference(NewRecords.CreateTime);
                    db.Pts_Records.Add(modelPts_Records);
                    //更新问题表待调整

                    upDateProblems.IsStart = false;
                    upDateProblems.HandlingUser = modelPts_Records.AssignToObjectID;
                    upDateProblems.ProblemStateID = modelPts_Records.ProblemStateID;
                    int result = db.SaveChanges();
                    return RedirectToAction("Details", "Problems", new { id = modelPts_Records.ProblemID });
                }
                else
                {
                    return Content("-1");
                }
            }
            catch (DbEntityValidationException dbEx)
            {
                return Content("-1");
            }
        }
        //研发人员回复问题
        // GET: /RecordS/Create

        public ActionResult YFCreate(Guid id)
        {
            Pts_Records modelRecords = new Pts_Records();
            modelRecords.ProblemID = id;
            Department clsDepartment = new Department();
            UserProfileModel userprofile = GetMyProfile();
            ViewBag.AssignTo = new SelectList(clsDepartment.GetDepartmentList(userprofile.Department), "DeptID", "DeptName");
            return View(modelRecords);
        }

        /// <summary>
        /// 研发回复问题
        /// </summary>
        /// <param name="pts_Records"></param>
        /// <returns></returns>

Mvc3QA/Views/RecordS/Create.cshtml
@model Mvc3QA.Models.Pts_Records
@using res = Resource.Views.Admin.Admin;
@{Mvc3QA.General.GeneralConfigInfo ci = ViewBag.CI as Mvc3QA.General.GeneralConfigInfo;}
@{
    ViewBag.Title = "回复问题";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/kindeditor/kindeditor.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/kindeditor/lang/zh_CN.js")" type="text/javascript"></script>
@Html.Action("QuestionCount", "Problems")
<div class="row-fluid">
  
    <div class="span12">
        @using (Html.BeginForm("Create", "Records", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>回复问题</legend>
                @Html.HiddenFor(model => model.ProblemID)
                <div class="control-group">
                    <label class="control-label">
                        处理方式</label>
                    <div class="controls">
                        <label class="radio">
                            <input type="radio" name="AssignType" id="dealing" value="1" checked="">
                            直接解决
                        </label>
                        <label class="radio">
                            <input type="radio" name="AssignType" id="transmit" value="2">
                            转交其他人处理
                        </label>
                        <label class="radio">
                            <input type="radio" name="AssignType" id="nodealing" value="3">
                            不解决
                        </label>
                    </div>
                </div>
                <div class="control-group" id="AssignedToDiv" style="display: none;">
                    <div class="control-label">
                        选择问题接收人或部门
                    </div>
                    <div class="controls">
                        @Html.DropDownList("AssignTo")<select id="AssignToObjectID" name="AssignToObjectID">
                            <option value="0">部门所有人可见</option>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <div class="control-label">
                        处理意见
                    </div>
                    <div class="controls">
                        @Html.TextAreaFor(model => model.Content, new { style = "width: 700px; height: 300px" })
                        @Html.ValidationMessageFor(model => model.Content)
                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary" id="BtnSubmit" name="BtnSubmit">
                        保存</button>
                    <span style="display: none;" id="Loading">提交中...</span>
                    <button class="btn">
                        取消</button>
                </div>
            </fieldset>
        }
        
    </div>
</div>
@section Js{
    <script type="text/javascript">   
        $(function () {
        $(":radio").click(
        function(){  
       if ($('input:radio[name="AssignType"]:checked').val()==2) {
       $("#AssignedToDiv").show();
     }else {
      $("#AssignedToDiv").hide();
    }
        }       
        );
       
       //默认加载
          var Did2 = $("#AssignTo").val();
               $("#AssignToObjectID").find("option").remove();  //清空                              
                $.post("@Url.Content("~/Problems/GetDeptUser/")", { id: Did2 }, function (data) {
                    if (data == "-1") {
                        alert("删除失败");
                    }
                    else {$.each(data,function(index,item){  $("<option></option>").val(item["Value"]).text(item["Text"]).appendTo($("#AssignToObjectID")); })                   
                   
                    }

                });
                //改变加载
         $("[name='AssignTo']").change(
        function () {
         
                var Did = $(this).attr("value");
               $("#AssignToObjectID").find("option").remove();  //清空                              
                $.post("@Url.Content("~/Problems/GetDeptUser/")", { id: Did }, function (data) {
                    if (data == "-1") {
                        alert("删除失败");
                    }
                    else {$.each(data,function(index,item){  $("<option></option>").val(item["Value"]).text(item["Text"]).appendTo($("#AssignToObjectID")); })                   
                   
                    }

                });
           
        }
       );
      
            $("#List").click(
                    function () {
                    var Did= $('input:[name="ProblemID"]').val();
           $.post("@Url.Content("~/Problems/AdminRecords")", { id: Did }, function (data) {
          $("#lB").empty();
           $("#lB").append(data);      
        });
                    })

        })
      $(function () {
            var editorContent = null;
            KindEditor.ready(function (K) {
                editorContent = K.create('textarea[name="Content"]', {
                    allowImageUpload: true,
                    uploadJson: '/admin/UploadFile'
                });
            });
          

            $("#BtnSubmit").click(function () {
                editorContent.html(ReplaceKESpace(editorContent.html()));
                editorContent.sync();
            });
        });
        function ProcessSuccess(re) {         
            $('#AjaxResult').html(re);
        }
    </script>
}

Mvc3QA/Views/RecordS/Delete.cshtml
@model Mvc3QA.Models.Pts_Records

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Pts_Records</legend>

    <div class="display-label">RecordID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RecordID)
    </div>

    <div class="display-label">Pts_Problems</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pts_Problems.Title)
    </div>

    <div class="display-label">CreateUser</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreateUser)
    </div>

    <div class="display-label">CreateTime</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreateTime)
    </div>

    <div class="display-label">Content</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Content)
    </div>

    <div class="display-label">Pts_ProblemState</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pts_ProblemState.StateName)
    </div>

    <div class="display-label">RecordClass</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RecordClass)
    </div>

    <div class="display-label">SrcStateID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SrcStateID)
    </div>

    <div class="display-label">SrcUserID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SrcUserID)
    </div>

    <div class="display-label">Course</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Course)
    </div>

    <div class="display-label">AssignType</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AssignType)
    </div>

    <div class="display-label">AssignStateID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AssignStateID)
    </div>

    <div class="display-label">AssignToObjectID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AssignToObjectID)
    </div>

    <div class="display-label">AssignTo</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AssignTo)
    </div>

    <div class="display-label">ResponseWorkTime</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ResponseWorkTime)
    </div>

    <div class="display-label">ResponseTotalTime</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ResponseTotalTime)
    </div>

    <div class="display-label">RealTimeCost</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RealTimeCost)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Mvc3QA/Views/RecordS/Details.cshtml
@model Mvc3QA.Models.Pts_Records

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Pts_Records</legend>

    <div class="display-label">RecordID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RecordID)
    </div>

    <div class="display-label">Pts_Problems</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pts_Problems.Title)
    </div>

    <div class="display-label">CreateUser</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreateUser)
    </div>

    <div class="display-label">CreateTime</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreateTime)
    </div>

    <div class="display-label">Content</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Content)
    </div>

    <div class="display-label">Pts_ProblemState</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pts_ProblemState.StateName)
    </div>

    <div class="display-label">RecordClass</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RecordClass)
    </div>

    <div class="display-label">SrcStateID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SrcStateID)
    </div>

    <div class="display-label">SrcUserID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SrcUserID)
    </div>

    <div class="display-label">Course</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Course)
    </div>

    <div class="display-label">AssignType</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AssignType)
    </div>

    <div class="display-label">AssignStateID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AssignStateID)
    </div>

    <div class="display-label">AssignToObjectID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AssignToObjectID)
    </div>

    <div class="display-label">AssignTo</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AssignTo)
    </div>

    <div class="display-label">ResponseWorkTime</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ResponseWorkTime)
    </div>

    <div class="display-label">ResponseTotalTime</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ResponseTotalTime)
    </div>

    <div class="display-label">RealTimeCost</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RealTimeCost)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Mvc3QA/Views/RecordS/Index.cshtml
@model IEnumerable<Mvc3QA.Models.Pts_Records>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            RecordID
        </th>
        <th>
            Pts_Problems
        </th>
        <th>
            CreateUser
        </th>
        <th>
            CreateTime
        </th>
        <th>
            Content
        </th>
        <th>
            Pts_ProblemState
        </th>
        <th>
            RecordClass
        </th>
        <th>
            SrcStateID
        </th>
        <th>
            SrcUserID
        </th>
        <th>
            Course
        </th>
        <th>
            AssignType
        </th>
        <th>
            AssignStateID
        </th>
        <th>
            AssignToObjectID
        </th>
        <th>
            AssignTo
        </th>
        <th>
            ResponseWorkTime
        </th>
        <th>
            ResponseTotalTime
        </th>
        <th>
            RealTimeCost
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RecordID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pts_Problems.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateUser)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pts_ProblemState.StateName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RecordClass)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SrcStateID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SrcUserID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignStateID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignToObjectID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignTo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ResponseWorkTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ResponseTotalTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RealTimeCost)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

Mvc3QA/Views/RecordS/YFCreate.cshtml
@model Mvc3QA.Models.Pts_Records
@using res = Resource.Views.Admin.Admin;
@{Mvc3QA.General.GeneralConfigInfo ci = ViewBag.CI as Mvc3QA.General.GeneralConfigInfo;}
@{
    ViewBag.Title = "研发回复问题";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/kindeditor/kindeditor.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/kindeditor/lang/zh_CN.js")" type="text/javascript"></script>
@Html.Action("QuestionCount", "Problems")
<div class="row-fluid">
  
    <div class="span12">
        @using (Html.BeginForm("YFCreate", "Records", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>研发回复问题</legend>
                @Html.HiddenFor(model => model.ProblemID)
                <div class="control-group">
                    <label class="control-label">
                        处理方式</label>
                    <div class="controls">
                        <label class="radio">
                            <input type="radio" name="AssignType" id="dealing" value="1" checked="">
                            直接解决
                        </label>
                        <label class="radio">
                            <input type="radio" name="AssignType" id="transmit" value="2">
                            解决方式
                        </label>
                        
                    </div>
                </div>
                <div id="AssignedToDiv" style="display: none;">
                <div class="control-group" >                   
                    <div class="controls">
                      <select  name="YFWay">
                            <option value="1">规划解决</option>
                            <option value="2">修改BUG</option>
                        </select>
                    </div>

                </div>
                <div class="control-group">
                <div class="control-label">
                    选择研发时间
                </div>
                <div class="controls">
                    @Html.EditorFor(model => model.YFTime)
                    @Html.ValidationMessageFor(model => model.YFTime)
                </div>
            </div>
            </div>

                <div class="control-group">
                    <div class="control-label">
                        处理意见
                    </div>
                    <div class="controls">
                        @Html.TextAreaFor(model => model.Content, new { style = "width: 700px; height: 300px" })
                        @Html.ValidationMessageFor(model => model.Content)
                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary" id="BtnSubmit" name="BtnSubmit">
                        保存</button>
                    <span style="display: none;" id="Loading">提交中...</span>
                    <button class="btn">
                        取消</button>
                </div>
            </fieldset>
        }
        
    </div>
</div>
@section Js{
    <script type="text/javascript">   
        $(function () {
         $('#YFTime').datepicker(); 
        $(":radio").click(
        function(){  
       if ($('input:radio[name="AssignType"]:checked').val()==2) {
       $("#AssignedToDiv").show();
     }else {
      $("#AssignedToDiv").hide();
    }
        }       
        );
       
       //默认加载
          var Did2 = $("#AssignTo").val();
               $("#AssignToObjectID").find("option").remove();  //清空                              
                $.post("@Url.Content("~/Problems/GetDeptUser/")", { id: Did2 }, function (data) {
                    if (data == "-1") {
                        alert("删除失败");
                    }
                    else {$.each(data,function(index,item){  $("<option></option>").val(item["Value"]).text(item["Text"]).appendTo($("#AssignToObjectID")); })                   
                   
                    }

                });
                //改变加载
         $("[name='AssignTo']").change(
        function () {
         
                var Did = $(this).attr("value");
               $("#AssignToObjectID").find("option").remove();  //清空                              
                $.post("@Url.Content("~/Problems/GetDeptUser/")", { id: Did }, function (data) {
                    if (data == "-1") {
                        alert("删除失败");
                    }
                    else {$.each(data,function(index,item){  $("<option></option>").val(item["Value"]).text(item["Text"]).appendTo($("#AssignToObjectID")); })                   
                   
                    }

                });
           
        }
       );
      
            $("#List").click(
                    function () {
                    var Did= $('input:[name="ProblemID"]').val();
           $.post("@Url.Content("~/Problems/AdminRecords")", { id: Did }, function (data) {
          $("#lB").empty();
           $("#lB").append(data);      
        });
                    })

        })
      $(function () {
            var editorContent = null;
            KindEditor.ready(function (K) {
                editorContent = K.create('textarea[name="Content"]', {
                    allowImageUpload: true,
                    uploadJson: '/admin/UploadFile'
                });
            });
          

            $("#BtnSubmit").click(function () {
                editorContent.html(ReplaceKESpace(editorContent.html()));
                editorContent.sync();
            });
        });
        function ProcessSuccess(re) {         
            $('#AjaxResult').html(re);
        }
    </script>
}