Mvc3QA/Controllers/ProblemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc3QA.Models;
using Common;
using res = Resource.Controllers.Admin.Admin;
using Mvc3QA.Models.Services;
using System.Web.Security;
using System.Web.Profile;
using Mvc3QA.General;
namespace Mvc3QA.Controllers
{
    [Authorize(Roles = "BusinessUsers")]
    public class ProblemsController : Controller
    {
        private questiononlineContext db = new questiononlineContext();
        GeneralConfigInfo configinfo = Mvc3QA.General.WebUtils.configinfo;
        //问题列表
        // GET: /Problems/

        public ViewResult Index(int? pageNo, int? cid, string sort, string order)
        {
            Problems clsProblems = new Problems();
            Category clsCategory = new Category();
            Pager pager = new Pager();
            int cateid = cid ?? 0;
            pager.PageNo = pageNo ?? 1;
            pager.PageSize = 20;
            if (cateid > 0)
                pager = clsProblems.GetReplyPaging(pager, clsCategory.GetCategoryIds(cateid), sort, string.IsNullOrWhiteSpace(order) ? "desc" : order, User.Identity.Name);
            else
                pager = clsProblems.GetReplyPaging(pager, cateid, sort, string.IsNullOrWhiteSpace(order) ? "desc" : order, User.Identity.Name);
            ViewBag.PageNo = pageNo ?? 1;//页码
            ViewBag.PageCount = pager.PageCount;//总页数            
            ViewBag.Cid = cateid;
            ViewBag.Sort = sort;
            ViewBag.Order = order;
            List<CategoryModel> catelist = clsCategory.getFCategoryList("1", "", " -- ");
            catelist.Insert(0, new CategoryModel
            {
                CateId = "0",
                CateName = res.SelectSubcategories
            });
            ViewData["CateId"] = new SelectList(catelist, "CateId", "CateName", cateid);
            return View(pager.Entity);
        }
        //
        // GET: /Problems/Details/5

        public ViewResult Details(Guid id)
        {
            var NewRecords = (from d in db.Pts_Records
                              where d.ProblemID == id
                              orderby d.CreateTime descending
                              select d).First();
            Category clsCategory = new Category();
            UserProfileModel userprofile = GetMyProfile();
            List<CategoryModel> catelist = clsCategory.getFCategoryList("1", "", " -- ");
            Pts_Problems clsPts_Problems = db.Pts_Problems.Find(id);
            ViewBag.CategoryID = catelist.Find(c => c.CateId.ToString() == clsPts_Problems.CategoryID.ToString()).CateName.ToString();
            Department clsDepartment = new Department();
            ViewBag.AssignTo = new SelectList(clsDepartment.GetDepartmentList(), "DeptID", "DeptName");
            ViewBag.Department = userprofile.Department;
            //显示修改按钮相关
            Problems clsProblems = new Problems();
            ViewBag.Edit = NewRecords.ProblemStateID.ToString() == "9c3f96c9-1869-41c4-92f5-f81c5f3e6e5c" ? "1" : "0";
            return View(clsPts_Problems);
        }

        //
        // GET: /Problems/Create

        public ActionResult Create()
        {
            string tid = "1";
            string cid = "1";
            UserProfileModel userprofile = GetMyProfile();
            ViewBag.showAssignTo = userprofile.Department;
            Department clsDepartment = new Department();
            Category clsCategory = new Category();
            ViewData["CategoryID"] = new SelectList(clsCategory.getFCategoryList(tid, "", " -- "), "CateId", "CateName", cid);
            ViewBag.AssignedTo = new SelectList(clsDepartment.GetDepartmentList(userprofile.Department), "DeptID", "DeptName");
            ViewBag.CurrentItem = "t" + tid;
            if (tid == "4")
                return View("AdminAlbumAdd");

            return View();
        }

        //
        // POST: /Problems/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Pts_Problems model)
        {
            //添加[ValidateInput(false)]特性，否则提交内容有html代码会报错
            if (ModelState.IsValid)
            {
                UserProfileModel userprofile = GetMyProfile();

                Pts_Problems obj = new Pts_Problems();
                Pts_Records modelPts_Records = new Pts_Records();
                Department clsDepartment = new Department();
                obj.ProblemID = Guid.NewGuid();
                obj.CreateTime = DateTime.Now;
                obj.CategoryID = model.CategoryID;
                obj.Title = Utils.FileterStr(model.Title);
                obj.Description = Utils.NoHTML(string.IsNullOrWhiteSpace(model.Description) ? "" : model.Description);
                obj.Content = Server.UrlDecode(Utils.DownloadImages(model.Content, "/Content/Upload/", configinfo.Weburl));
                //obj.ip = Utils.GetIP();               
                obj.CreateUser = User.Identity.Name;
                obj.StartTime = model.StartTime;
                obj.CloseTime = model.CloseTime;
                obj.AssignedTo = model.AssignedTo;
                obj.AssignedToUser = model.AssignedToUser;
                obj.IsStart = true;
                obj.IsClosed = false;
                obj.HandlingUser = model.AssignedToUser;
                obj.CreatUserName = userprofile.NickName;
                //回复表中添加记录                  
                modelPts_Records.RecordID = Guid.NewGuid();
                modelPts_Records.AssignStateID = new Guid("00000000-0000-0000-0000-000000000000");
                modelPts_Records.AssignTo = model.AssignedTo;
                modelPts_Records.AssignToObjectID = model.AssignedToUser;
                modelPts_Records.AssignType = 0;
                modelPts_Records.Content = "新提交问题";
                //modelPts_Records.Title = pts_Records.Title;
                modelPts_Records.CreateUser = User.Identity.Name;
                modelPts_Records.CreateTime = DateTime.Now;
                modelPts_Records.ProblemID = obj.ProblemID;
                modelPts_Records.SrcStateID = new Guid("00000000-0000-0000-0000-000000000000");
                modelPts_Records.SrcUserID = User.Identity.Name;
                modelPts_Records.Describe = "新提交问题";
                modelPts_Records.ListOrder = 1;
                //提交问题记录相关信息
                if (model.AssignedToUser == "0")
                {

                    modelPts_Records.Course = userprofile.NickName + "-->" + clsDepartment.GetDepartmentName(model.AssignedTo) + "(部门所有人)";

                }
                else
                {
                    modelPts_Records.Course = userprofile.NickName + "-->" + clsDepartment.GetDepartmentName(model.AssignedTo) + "(" + GetUserProfile(model.AssignedToUser) + ")";

                }
                //提交问题后状态
                modelPts_Records.ProblemStateID = clsDepartment.GetProblemState(model.AssignedTo);
                obj.ProblemStateID = clsDepartment.GetProblemState(model.AssignedTo);//问题表中状态               
                db.Pts_Problems.Add(obj);
                db.Pts_Records.Add(modelPts_Records);
                db.SaveChanges();


                return RedirectToAction("Index", new { tid = 1, cid = obj.CategoryID });
            }
            return View(model);
        }

        //
        // GET: /Problems/Edit/5

        public ActionResult Edit(int id)
        {
            Pts_ProblemCategory pts_problemcategory = db.Pts_ProblemCategory.Find(id);
            return View(pts_problemcategory);
        }

        //
        // POST: /Problems/Edit/5

        [HttpPost]
        public ActionResult Edit(Pts_ProblemCategory pts_problemcategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pts_problemcategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pts_problemcategory);
        }

        //
        // GET: /Problems/Delete/5

        public ActionResult Delete(int id)
        {
            Pts_ProblemCategory pts_problemcategory = db.Pts_ProblemCategory.Find(id);
            return View(pts_problemcategory);
        }

        //
        // POST: /Problems/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Pts_ProblemCategory pts_problemcategory = db.Pts_ProblemCategory.Find(id);
            db.Pts_ProblemCategory.Remove(pts_problemcategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        /// <summary>
        /// 根据部门获取用户列表
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetDeptUser(string id)
        {
            try
            {
                if (Request.IsAjaxRequest())
                {
                    List<SelectListItem> ListS = new List<SelectListItem>();
                    SelectListItem sl = new SelectListItem();
                    sl.Text = "部门所有人可见";
                    sl.Value = "0";
                    ListS.Add(sl);
                    MembershipUserCollection users = Membership.GetAllUsers();
                    foreach (MembershipUser item in users)
                    {
                        sl = new SelectListItem();
                        ProfileBase objProfile = System.Web.Profile.ProfileBase.Create(item.UserName);
                        if (GetUserProfileItem(objProfile, "Department") == id)
                        {
                            sl.Text = GetUserProfileItem(objProfile, "NickName");

Mvc3QA/Views/Shared/_Console.cshtml
<div class="subnav" style="margin-bottom: 20px;">
    <ul class="nav nav-pills" id="sort">
        <li><a href="#labels" title="Total">问题总数<span class="badge badge-info" style="margin-left: 5px;">@ViewBag.QuestionCount</span></a></li>
        <li><a href="#labels" title="NewQuestion">新提交问题<span class="badge badge-info" style="margin-left: 5px;">@ViewBag.NewQuestion</span></a></li>
        <li><a href="#badges" title="MyReplay">我的待处理问题<span class="badge badge-warning" style="margin-left: 5px;">@ViewBag.MyReplayCount</span></a></li>
        <li><a href="#thumbnails" title="MySolvedQuestion">我的已解决问题<span class="badge badge-success"
            style="margin-left: 5px;">@ViewBag.MySolvedQuestionCount</span></a></li>
        <li><a href="#thumbnails" title="SolvedQuestion">已解决问题<span class="badge badge-success"
            style="margin-left: 5px;">@ViewBag.SolvedQuestionCount</span></a></li>
        <li>@Html.ActionLink("返回问题列表", "Index", "Problems")</li>
    </ul>
</div>

Mvc3QA/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null)
{
    return;
}
@{
    Model.OnPreRender();/* Select items from collection */
}
<div id="grid-mvc" class="grid-outer @(Model.EnablePaging ? "paged" : string.Empty)">
    @* Draw grid top items infomation panel *@
    <div class="grid-wrap">
        <table class="grid-table" data-lang="@Model.Language">
            @* Draw grid header *@
            <thead>
                <tr>
                    @foreach (IGridColumn column in Model.Columns)
                    {
                        @Html.Raw(column.HeaderRenderer.Render(column, column.Title))
                    }
                </tr>
            </thead>
            <tbody>
                @if (Model.ItemsCount == 0)
                {
                    <tr class="grid-empty-text">
                        <td colspan="@Model.Columns.Count()">
                            @Model.EmptyGridText
                        </td>
                    </tr>
                }
                else
                {
                    foreach (object item in Model.ItemsToDisplay)
                    {
                    <tr class="grid-row">
                        @foreach (IGridColumn column in Model.Columns)
                        {
                            @Html.Raw(column.CellRenderer.Render(column, column.GetCell(item).ToString()))
                        }
                    </tr>
                    }
                }
            </tbody>
        </table>
        @if (Model.EnablePaging && Model.Pager != null && Model.Pager.PageCount > 1)
        {
            <div class="grid-footer">
                <div class="grid-footer-info">
                   当前页 @(((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize) + 1)
                    - @(((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize) + Model.DisplayingItemsCount)
                    (@Model.ItemsCount)
                </div>
                @Html.Partial("_GridPager", Model.Pager)
            </div>
        }
@* Draw pager *@
    </div>
</div>
@* Init Grid.Mvc client script *@
<script type="text/javascript">
    window.GridMvc = $("#grid-mvc").gridmvc();
</script>

Mvc3QA/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.IGridPager
@if (Model == null)
{
    return;
}
<div class="grid-pager">
    @if (Model.CurrentPage > 1)
    {
        <a class="pager-link" href="@Model.GetLinkForPage(Model.CurrentPage - 1)">上一页</a>
    }
    @if (Model.StartDisplayedPage > 1)
    {
        <a class="pager-link" href="@Model.GetLinkForPage(1)">1</a>
        if (Model.StartDisplayedPage > 2)
        {
            <a class="pager-link" href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a>
        }
    }
    @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
    {
        if (i == Model.CurrentPage)
        {
            <span class="pager-text">@i</span>
        }
        else
        {
            <a class="pager-link" href="@Model.GetLinkForPage(i)">@i</a>
        }
    }
    @if (Model.EndDisplayedPage < Model.PageCount)
    {
        if (Model.EndDisplayedPage < Model.PageCount - 1)
        {
            <a class="pager-link" href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a>
        }
        <a class="pager-link" href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a>
    }
    @if (Model.CurrentPage < Model.PageCount)
    {
        <a class="pager-link" href="@Model.GetLinkForPage(Model.CurrentPage + 1)">下一页</a>
    }
</div>

Mvc3QA/Views/Shared/_Layout.cshtml
@using res = Resource.Views.Shared.Shared;
@{
    string weblang = Resource.Models.Web.Web.Lang != "" ? Resource.Models.Web.Web.Lang + "." : "";
    Mvc3QA.General.GeneralConfigInfo ci = ViewBag.CI as Mvc3QA.General.GeneralConfigInfo;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" content="" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/themes/css/custom-theme/jquery-ui-1.8.16.custom.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Styles/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    @* <link href="@Url.Content("~/Content/Styles/bootstrap-responsive.min.css")" rel="stylesheet" type="text/css" />*@
    <link href="@Url.Content("~/Content/themes/third-party/jQuery-UI-Date-Range-Picker/css/ui.daterangepicker.css")" media="screen" rel="Stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Styles/site.css")" rel="stylesheet" type="text/css" />
    @RenderSection("CSS", false)
    <script src="@Url.Content("~/Content/bootstrap/js/jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/themes/js/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap-dropdown.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap-modal.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap-confirm.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap-tab.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap-tooltip.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap-popover.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap-button.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/application.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/themes/third-party/jQuery-UI-Date-Range-Picker/js/date.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/themes/third-party/jQuery-UI-Date-Range-Picker/js/daterangepicker.jQuery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/Web.Lang." + @weblang + "js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/Admin.js")" type="text/javascript"></script>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="brand" href="#">问题在线管理系统</a>
                <div class="nav-collapse">
                    <ul class="nav">
                        <li class="active">@Html.ActionLink("首页","Index","Home")</li>
                        <li><a href="#">帮助手册</a></li>
                      
                    </ul>
                    <form class="navbar-search pull-left" action="">
                    <input type="text" class="search-query span2" placeholder="搜索">
                    </form>
                    <ul class="nav pull-right">
                        @Html.Partial("_LogOnPartial")
                    </ul>
                </div>
                <!-- /.nav-collapse -->
            </div>
        </div>
        <!-- /navbar-inner -->
    </div>
    <div class="container">
        @RenderBody()
    </div>
    @RenderSection("JS", false)
</body>
</html>

Mvc3QA/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated)
{
    <li><a href="#">提交问题</a></li>
    <li class="divider-vertical"></li>
     <li><a href="#">处理问题</a></li>
    <li class="divider-vertical"></li>
    <li>
                @Html.ActionLink("后台管理", "Index", "QAAdmin/Admin")
            </li>
     <li class="divider-vertical"></li>
    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
        @User.Identity.Name <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                @Html.ActionLink("修改密码", "ChangePassword", "Account")
            </li>
             <li class="divider"></li>
            <li>@Html.ActionLink("详细信息", "UCenter", "Account")</li>
            <li class="divider"></li>
            <li>
                @Html.ActionLink("注销", "LogOff", "Account")
            </li>
           
        </ul>
    </li>
}
else
{   
    <li class="divider-vertical"></li>
    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">游客 <b
        class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("登录", "LogOn", "Account")</li>
            <li class="divider"></li>
            <li>@Html.ActionLink("注册", "Register", "Account")</li>
        </ul>
    </li>
}

Mvc3QA/Views/Shared/_OperatePartial.cshtml
<div class="span3">
    <div class="well sidebar-nav">
        <ul class="nav nav-list">
            <li class="nav-header">功能</li>
            <li class="active"><a href="#"><i class="icon-white icon-home"></i>首页</a></li>
            <li><a href="#"><i class="icon-book"></i>类库</a></li>
            <li><a href="#"><i class="icon-pencil"></i>应用</a></li>
            <li class="nav-header">系统管理</li>
            <li><a href="@Url.Content("~/Accounts_Users/Index")"><i class="icon-user"></i>用户管理</a></li>
            <li><a href="@Url.Content("~/Accounts_Department/Index")"><i class="icon-cog"></i>部门管理</a></li>
            <li><a href="@Url.Content("~/Pts_ProblemType/Index")"><i class="icon-cog"></i>类别管理</a></li>
            <li><a href="@Url.Content("~/Pts_ProblemState/Index")"><i class="icon-cog"></i>状态管理</a></li>
             <li><a href="@Url.Content("~/Pts_Problems/Index")"><i class="icon-cog"></i>问题管理</a></li>
            <li class="divider"></li>
            <li><a href="#"><i class="icon-flag"></i>帮助</a></li>
        </ul>
    </div>
    <!--/.well -->
</div>

Mvc3QA/Views/Shared/_UserProfile.cshtml
@model Mvc3QA.Models.UserProfileModel
@using res = Resource.Views.Shared.Shared;
@{
    string weblang = Resource.Models.Web.Web.Lang != "" ? Resource.Models.Web.Web.Lang : "zh-cn";
    Mvc3QA.General.GeneralConfigInfo ci = ViewBag.CI as Mvc3QA.General.GeneralConfigInfo;
}
<div class="uitem">@(res.UserProfile)</div>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div id="Loading">@Resource.Views.Home.Home.Ajax_Wait</div>
<div id="AjaxResult">
</div>
@using (Ajax.BeginForm("AjaxUserProfile", new AjaxOptions { LoadingElementId = "profileloading", InsertionMode = InsertionMode.InsertBefore, OnSuccess = "UserProfileSubmitSuccess" }))
{
    <div id="commentform">
        @Html.HiddenFor(m => m.Medals)
        <div class="control-group">
            <div class="control-label">
                @Html.LabelFor(m => m.NickName)
            </div>
            <div class="controls">
                @Html.TextBoxFor(m => m.NickName)
                @Html.ValidationMessageFor(m => m.NickName)
            </div>
        </div>
          <div class="control-group">
            <div class="control-label">
                @Html.LabelFor(m => m.Gender)
            </div>
            <div class="controls">
                  @Html.DropDownList("Gender")
            </div>
        </div>
        <div class="control-group">
            <div class="control-label">
                @Html.LabelFor(m => m.Department)
            </div>
            <div class="controls">
                  @Html.DropDownList("Department")
            </div>
        </div>
        <div class="control-group">
            <div class="control-label">
                @Html.LabelFor(m => m.Birth)
            </div>
            <div class="controls">
                @Html.TextBoxFor(m => m.Birth, new { @id = "Birth" })
                @Html.ValidationMessageFor(m => m.Birth)
            </div>
        </div>
         <div class="control-group">
            <div class="control-label">
                @Html.LabelFor(m => m.Phone)
            </div>
            <div class="controls">
                @Html.TextBoxFor(m => m.Phone)
                @Html.ValidationMessageFor(m => m.Phone)
            </div>
        </div>

       
        <div @if (ci.IfSendReplyEmail == 2)
             {@Html.Raw("style=\"display:none;\"")}>
           <div class="control-group">
            <div class="control-label">
                @Html.LabelFor(m => m.Email)
            </div>
            <div class="controls">
                @Html.TextBoxFor(m => m.Email)
                @Html.ValidationMessageFor(m => m.Email)
            </div>
            </div>
        </div>
        <div class="control-group" @if (ci.IfSendReplyEmail == 2)
                           {@Html.Raw("style=\"display:none;\"")}>
            <div class="control-label">
                @Html.LabelFor(m => m.IsSendEmail)
            </div>
            <div class="controls">
              
                <label for="IsSendEmail_y" class="radio">
                    @res.Send
                      <input type="radio" value="1" name="IsSendEmail" id="IsSendEmail_y"  @if (Model.IsSendEmail == "1")
                                                                                     {@Html.Raw("checked=\"checked\"")}/>
                    </label>
              
                <label for="IsSendEmail_n" class="radio">
                    @res.Donotsend
                      <input type="radio" value="2" name="IsSendEmail" id="IsSendEmail_n" @if (Model.IsSendEmail != "2")
                                                                                    {@Html.Raw("checked=\"checked\"")}/>
                    </label>
            </div>
        </div>
       
        <div style="width: 500px" class="editor_ubb">
          
        </div>
       
        <p>
            <input type="submit" value="@Resource.Views.Home.Home.Submit" id="BtnSubmit" class="btn"/>
            <span id="profileloading" style="display: none;">
                <img src="/Content/images/loading/loader.gif" /></span>
        </p>
    </div>
}
<script type="text/javascript">
    $(function () {
        //        $("#Birth").daterangepicker();
        $('#Birth').datepicker({
            inline: true
        });
    });
</script>